services:

  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    hostname: 'gitlab.corso.local'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.corso.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 5022
    networks:
      - net-devops
    ports:
      - '9080:80'
      - '5443:443'
      - '5022:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    shm_size: '256m'

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    networks:
      - net-devops
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  
  jenkins-ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-ssh-agent
    hostname: jenkins-ssh-agent
    networks:
      - net-devops

  # /opt/sonarqube/data: data files, such as the embedded H2 database and Elasticsearch indexes
  # /opt/sonarqube/logs: contains SonarQube logs about access, web process, CE process, Elasticsearch logs
  # /opt/sonarqube/extensions: for 3rd party plugins
  # docker run --name sonarqube-custom -p 9000:9000 sonarqube:community

  sonar:
    image: sonarqube:latest
    container_name: sonar
    hostname: sonar
    networks:
      - net-devops
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions 


volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:


networks:
  net-devops:
    driver: bridge

